// Automatically generated by astro-icon
// 97c0e55d57d161c7d0c031db8454584a99a2b7fff4d3025f2d7803d6f50fe7d7

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "clapperboard"
		| "login"
		| "popcorn"
		| "search"
		| "user";
}