// Automatically generated by astro-icon
// 86fc1409c9d68f638371614fdbe666799031e978f1606136bd843ccbed4a927f

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "back"
		| "clapperboard"
		| "loader"
		| "login"
		| "logout"
		| "popcorn"
		| "search"
		| "user";
}